name: Deploy to EC2

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Add SSH key for EC2 instance (use the secret added in GitHub)
    - name: Add SSH Key
      run: |
        echo "$SERVER_SSH_KEY" 
      env:
        AWS_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}  # Make sure this secret is added in GitHub

    # Step 3: Push code to the EC2 instance
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.211.28.15 << EOF
          cd /home/ubuntu/new  # Navigate to your project directory on the EC2 instance
          git pull origin master      # Pull the latest changes from the main branch
          # Optionally, run any build or deployment scripts here
          # For example, you can restart your app or server
        EOF
