name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Connect to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.211.28.15 "echo 'SSH successful'"
