name: Deploy to EC2

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2 and run commands
      uses: appleboy/ssh-action@master
      with:
       host: 13.211.28.15
       username: ubuntu
       key: ${{ secrets.SERVER_SSH_KEY }}
       script: |
       # Commands to run on the EC2 instance
        echo "Hello, EC2!"
        ls
